refactoring

diff --git a/03-gitops/apps/demo/online-boutique/base/loadgenerator.yaml b/03-gitops/apps/demo/online-boutique/base/loadgenerator.yaml
--- a/03-gitops/apps/demo/online-boutique/base/loadgenerator.yaml
+++ b/03-gitops/apps/demo/online-boutique/base/loadgenerator.yaml
@@ -28,70 +28,64 @@ spec:
         app: loadgenerator
       annotations:
         sidecar.istio.io/rewriteAppHTTPProbers: "true"
+        sidecar.istio.io/inject: "true"
     spec:
       serviceAccountName: loadgenerator
       terminationGracePeriodSeconds: 5
-      restartPolicy: Always
       securityContext:
         fsGroup: 1000
         runAsGroup: 1000
         runAsNonRoot: true
         runAsUser: 1000
       initContainers:
-      - command:
-        - /bin/sh
-        - -exc
-        - |
-          MAX_RETRIES=12
-          RETRY_INTERVAL=10
-          for i in $(seq 1 $MAX_RETRIES); do
-            echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
-            STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
-            if [ $STATUSCODE -eq 200 ]; then
-                echo "Frontend is reachable."
-                exit 0
-            fi
-            echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
-            sleep $RETRY_INTERVAL
-          done
-          echo "Failed to reach frontend after $MAX_RETRIES attempts."
-          exit 1
-        name: frontend-check
-        securityContext:
-          allowPrivilegeEscalation: false
-          capabilities:
-            drop:
-              - ALL
-          privileged: false
-          readOnlyRootFilesystem: true
-        image: busybox:latest
-        env:
-        - name: FRONTEND_ADDR
-          value: "frontend:80"
+        - name: frontend-check
+          image: curlimages/curl:8.5.0
+          command:
+            - /bin/sh
+            - -ec
+            - |
+              MAX_RETRIES=12
+              RETRY_INTERVAL=10
+              for i in $(seq 1 $MAX_RETRIES); do
+                echo "Attempt $i: Curling frontend: ${FRONTEND_ADDR}..."
+                HTTP_STATUS=$(curl -k -s -o /dev/null -w "%{http_code}" https://${FRONTEND_ADDR})
+                if [ "$HTTP_STATUS" = "200" ]; then
+                    echo "Frontend is reachable."
+                    exit 0
+                fi
+                echo "Error: HTTP status $HTTP_STATUS"
+                sleep $RETRY_INTERVAL
+              done
+              echo "Failed to reach frontend after $MAX_RETRIES attempts."
+              exit 1
+          env:
+            - name: FRONTEND_ADDR
+              value: "online-boutique.demo"
+
       containers:
-      - name: main
-        securityContext:
-          allowPrivilegeEscalation: false
-          capabilities:
-            drop:
-              - ALL
-          privileged: false
-          readOnlyRootFilesystem: true
-        image: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator:v0.10.2
-        env:
-        - name: FRONTEND_ADDR
-          value: "frontend:80"
-        - name: USERS
-          value: "10"
-        - name: RATE
-          value: "1"
-        resources:
-          requests:
-            cpu: 300m
-            memory: 256Mi
-          limits:
-            cpu: 500m
-            memory: 512Mi
+        - name: main
+          image: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator:v0.10.2
+          env:
+            - name: FRONTEND_ADDR
+              value: "online-boutique.demo"
+            - name: USERS
+              value: "10"
+            - name: RATE
+              value: "1"
+          securityContext:
+            allowPrivilegeEscalation: false
+            capabilities:
+              drop:
+                - ALL
+            privileged: false
+            readOnlyRootFilesystem: true
+          resources:
+            requests:
+              cpu: 300m
+              memory: 256Mi
+            limits:
+              cpu: 500m
+              memory: 512Mi
 ---
 apiVersion: v1
 kind: ServiceAccount
